### ISSUE TITLE
Snap support

### ISSUE THREAD

**Issue by jyourstone** [terrycain/certbot-dns-azure#13]
Hi,

Any chance of adding this as a Snap package? I have Certbot installed using Snap and cannot use this plugin because of that.

**Comment by cpressland** [comment]
@jyourstone - we're looking at adding support for this. This project was written by @terrycain who has since left Bink, we're seeing if he wants to take over maintenance of the project as a personal thing, of if its better to donate it to certbot team (they didn't want it last time we asked).

If all else fails, I'll get up to speed with this project and snaps in the coming weeks.

**Comment by jyourstone** [comment]
I understand, sounds great that you're looking into adding support for Snap.
Thank you for keeping me in the loop.

**Comment by terrycain** [comment]
Hey sorry for the delay, am hoping to look at this on the weekend, should be simple enough.

**Comment by terrycain** [comment]
So I've attempted to make a snap but its now pending manual review :/. Once its out if you wouldn't mind testing it that would be great.

**Comment by jyourstone** [comment]
Great news, thank you!
I'll test it out when it has been reviewed.

**Comment by terrycain** [comment]
https://snapcraft.io/certbot-dns-azure - snap here 
https://github.com/terrycain/certbot-dns-azure#via-snap---not-tested-yet - docs here

**Comment by jyourstone** [comment]
It's working great, thank you very much!
